### ISSUE TITLE
1.0 Roadmap

### ISSUE THREAD

**Issue by floating-cat** [floating-cat/S1-Next#31]
Dependecies:
- [ ] Use Moshi instead Jackson because Moshi has less methods than Jackson and easy to customize how values are converted to and from JSON.
- [ ] Use `auto-value-moshi` to simplify models.
- [ ] Remove `commons-lang3` in order to reduce methods count.
- [ ] Two-way data binding.
- [ ] Remove `preference-v14` because it is troublesome (we need add styles for different Android versions) and inconsistent with the default platform style.
- [ ] Vector Drawables from Supprot library and use `android:tint` for vector asset. (We should test this before Android 5.0)
- [ ] Day/night mode from Android Support library. (Auto-switching or not?)
- [ ] Rx Preferences?

Code:
- [ ] Make code more simple.
- [ ] Do not extend `Account` for some models, because it is impossible to implement correct equality method for inheritance if we add new fields (see Effective Java Item 8).
- [ ] Remove unneeded getters for models.
- [ ] Separate transformation (for JSON deserialization) related code from models.
- [ ] Do not create Retrofit API endpoints (which includes `OkHttpClient` and JSON related class) in UI-thread because this is a little time consuming (XX ms?).
- [ ] Use database and others instead of `NonUIFragment`.

Code style:
- [ ] Remove unneeded blank lines after class/interface declaration.
- [ ] Add blank lines for empty block structure.
- [ ] Do not use Hungarian notation ("m" prefix).

UI:
- [ ] Tweak color palette for themes.
- [ ] Tweak app icon (primary color, color gradient and shadow).
- [ ] Remove shortcut to change theme in drawer?
- [ ] Add placeholder for images.
- [ ] Redesign `ReplyAcitivty` (Toolbar for supporting `[s][/s]` or something else).

Feature:
- [ ] Show high resolution if we click avatar. (Drawer and threads)
- [ ] Support 安全提问.
- [ ] Support posting a new thread?
- [ ] Support edit?

Android N:
- [ ] Can open `ReplyActivity` in new window.
- [ ] Data Saver prompt for images.
- [ ] Launcher shortcuts for specific forums or threads.
- [ ] Scoped directory access.

Others:
- [ ] Use public account for Bugsnag.

**Comment by smy20011** [comment]
遇到了65535方法数的坑么？multdex方案不喜欢还是？
双向绑定打算怎么做？

**Comment by floating-cat** [comment]
我现在都是用 Instatn Run 了，Instant Run 本身就是使用 multidex 的，所以 65536 对我影响不是很大。
不过我觉得从长远来看，还是应该减少一些方法过多的依赖， Jackson 有 1w 多个方法 （moshi 只有 1k 多的方法数，而且这部分的代码我也替换的差不多了），而 `commons-lang3` 在现在的应用用到的地方也不是很多。
[Android Studio 2.1 里已经支持 Data Binding 的双向判定了](https://halfthought.wordpress.com/2016/03/23/2-way-data-binding-on-android)。实际上当前应用里有部分地方滥用了 Data binding，所以我想把这部分内容改简单点，顺便用 双向绑定 把代码再改改。
