### ISSUE TITLE
0.2.0 Roadmap

### ISSUE THREAD

**Issue by floating-cat** [floating-cat/S1-Next#4]
**High priority**
- [x] Rely (with floating action button), not support Emoji. 8d73f5042f769c636144b9f2ae31d9083c0698c2
- [x] Multi-touch for image. ae89360a080b0d21b3f9aa924df74d0d506c8cfc
- [x] Log out. 101d0e6caef86c93bb9c19a8fe55132b2c688529
- [x] Action Bar can scroll off screen with the content and come back when the user reverse-scrolls, same to floating action button.

**Normal priority**
- [x] Support all text color for reply. 3af009e7137b3e0435664bd96de3daca43520bf9
- [x] Encode HTML entities for post title. ddbd6b1cf90e9422b12096569c2f1015c9318ace
